# See https://docs.codecov.io/docs/codecov-yaml
codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'

  # status:
  #   project: yes
  #   patch: yes
  #   changes: no

  status:
    # WIP: https://docs.codecov.io/docs/commit-status#patch-status
    # patch: off

    # WIP: https://docs.codecov.com/docs/common-recipe-list#ease-target-coverage
    project:
      default:
        threshold: 5%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'header, diff'
  behavior: default
  require_changes: no
